### PR TITLE
Fix var function inside color functions

### LINKED ISSUE #196: var function inside color functions cannot be parsed
Thank you for this library. I just started playing around with it and it works really good so far.

But I just noticed that parsing a rule like the following fails:

```css
a {
    background: rgba(var(--some-rgb) , 0.1);
}
```

The reason is that the var is inside the rgba function. If strict mode is enabled, this error is given: `Token “,” (1) not found. Got “var(-”.`

But this is valid CSS, see here for example: https://stackoverflow.com/a/41265350/1044527

UPDATE: fails also for `rgb(var(--some-rgb))`

### PR DESCRIPTION
**Pull request by digilist**
I tried to fix #196. Not sure if it is good solution, but at least it works ;)

### CODE REVIEW

File: lib/Sabberworm/CSS/Value/Color.php [hunk 1]
```diff
@@ -39,10 +39,31 @@ public static function parse(ParserState $oParserState) {
...
+				}
+
+				if ($bContainsVar && $oParserState->comes(')')) {
+					// With a var argument the function can have fewer arguments and the assignment to the color
+					// channels does not make sense
+					if ($i < $iLength - 1) {
+						// Add remaining characters to last item
+						$remainingChars = substr($sColorMode, $i + 1);
+						$aColor[$sColorMode[$i] . $remainingChars] = $aColor[$sColorMode[$i]];
+						unset($aColor[$sColorMode[$i]]);
```
Comment (digilist) [inline lib/Sabberworm/CSS/Value/Color.php:61]: I do not really like this solution but, but it's necessary as the array keys are used in the render function below to define the color function. And because of the nature of `var()` it's not possible to easily tell which arguments are defined through the variable.

If it's not clear what I mean: `rgba(var(--rg), 255)` is valid CSS code and the variable value can contain a comma, so it's valid CSS and in the parser it's hard to tell whether it's for red and green. It's somehow possible to identify it, but this will result in quite some code to identify all combinations and I am not sure if its necessary.

Comment (sabberworm) [reply lib/Sabberworm/CSS/Value/Color.php:61]: What if we parse colors that contain variables not as a `Color` instance but just an instance of a generic `CSSFunction`? I don’t see the additional value (pun intended) of using a specialized class when we can’t use it for any of the specializations we built it for…

**Comment by westonruter** [comment]
This should also fix #186.

File: lib/Sabberworm/CSS/Value/Color.php (hunk 1 above)
Comment (digilist) [reply lib/Sabberworm/CSS/Value/Color.php]: Good idea, I updated it as suggested.

**Comment by westonruter** [comment]
@sabberworm Anything else you'd like to see from this? We'd like to include it in the v2.0 release of the AMP plugin for WordPress.

**Comment by sabberworm** [comment]
@westonruter No, I just haven’t had time to do a proper review yet. I only wonder if it would be possible to solve this case generically as opposed to special-casing the color parsing. Next we’ll have someone wanting to use variables in `url()` and we’ll have to add a special case there.
